blog/urls.py
from django.urls import path
from . import views

app_name= 'blog'

urlpatterns = [ 
    path('', views.all_blogs, name="all_blogs"), 
    path('<int:blog_id>/', views.blog_detail, name="blog_detail"), 
]

myprofile/urls.py
from django.contrib import admin
from django.urls import path, include
from portfolio import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('blog/', include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
	title=models.CharField(max_length=20)
	description=models.TextField(max_length=200)
	url=models.URLField(blank=True)
	# image=models.ImageField(upload_to='blog/images/')

	def __str__(self):
		return self.title

portfolio/models.py
from django.db import models

class Profile(models.Model):
	title= models.CharField(max_length=20)
	description= models.CharField(max_length=40)
	image=models.ImageField(upload_to='portfolio/images/')
	url=models.URLField(blank=True)

	def __str__(self):
		return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

# Create your views here.
def all_blogs(req):
	# blog=Blog.objects.order_by('date')[:5]// ordered by desc and last 5 records
	blog=Blog.objects.all()
	return render(req,'blog/all_blogs.html',{'blog':blog})

def blog_detail(req,blog_id):
	blog=get_object_or_404(Blog,pk=blog_id)
	return render(req,'blog/blog_detail.html',{'blog':blog})
 

portfolio/views.py
from django.shortcuts import render
from .models import Profile

# Create your views here.
def home(req):
	profile=Profile.objects.all()
	return render(req,'portfolio/home.html',{'profile':profile})

blog/templates/blog/all_blogs.html
 
{% extends 'portfolio/base.html' %}

{% block content %}
<h1>All blogs</h1>
<h5>Nick has written total {{blog.count}} blog{{ blog.count|pluralize }}</h5>

{% for bg in blog%}
<a href=""><h2>{{bg.title}}</h2></a>
<h3>{{bg.description}}</h3>
{% endfor %}

{% endblock %}

blog/templates/blog/blog_detail.html
<h2>Blog Detail</h2>

<h3>{{blog.title|upper}}</h3>
<h4>{{blog.description}}</h4>

myprofile/templates/myprofile/home.html
<h3>Hi</h3>

portfolio/templates/portfolio/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My Portfolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>


    <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
     

{% block content %}

{% endblock %}
  </body>
}
}
</html>

portfolio/templates/portfolio/home.html
 
 
{% extends 'portfolio/base.html' %}

{% block content %}

 <h1>Welcome to Nick's Profile 😊 </h1>

<br/>
<a href="{% url 'blog:all_blogs' %}">All Blogs</a>
{% for proj in profile %}
<h2>{{proj.title}}</h2>
<h3>{{proj.description}}</h3>
<img src={{proj.image.url}} width="10%" /><br/>
{% if proj.url %}
<a href={{proj.url}}>Link</a>
{% endif %}

{% endfor %}
 
{% endblock %}